services:
  pog-scraper:
    build: .
    tty: true
    platform: linux/amd64
    image: asia-northeast1-docker.pkg.dev/poginfo/pog-info-scraper/pog-scraper:latest
    working_dir: /app
    command: [
      "uv",
      "run",
      "python",
      "-m",
      "app.presentation.debug.info_main"
    ]
    env_file:
      - .env
