[project]
name = "poginfo-scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.3.0",
    "selenium>=4.34.0",
    "pydantic>=2.0.0",
    "requests>=2.31.0",
]
