service: pog-scraper

provider:
  name: aws
  region: ${env:AWS_REGION}
  ecr:
    images:
      pog-scraper:
        path: ./
        platform: linux/amd64
functions:
  POGScraper:
    memorySize: 2048
    timeout: 60
    image:
      name: pog-scraper
      command:
        - app.info_handler
      environment:
        GROUP_NAME: ${env:POG_GROUP_NAME}
        USER_ID: ${env:POG_USER_ID}
        PASSWORD: ${env:POG_PASSWORD}

    name: pog-scraper-serverless
    description: serverless frameworkを使ってデプロイしたLambda
