name: Deploy to AWS Lambda

on:
  pull_request:
    branches:
      - main

env:
  ECR_REPOSITORY: pog-scraper
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: install-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install serverless
        run: npm install -g serverless

      - name: severless deploy
        run: sls deploy --stage production --verbose --force
